spring:
  application:
    name: sistema-provas

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sistema_provas}
    username: ${DB_USERNAME:sistema_provas}
    password: ${DB_PASSWORD:sistema_provas}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: Fo9ewcKiFjRuQxcSryuE87lfcg71UL3qpMAYcJP3pAE=
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG