spring:
  application:
    name: sistema-provas

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sistema_provas}
    username: ${DB_USERNAME:sistema_provas}
    password: ${DB_PASSWORD:sistema_provas}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: C7xODW6EaqByz6kZw11QIIofxbDVZAq7J/4r5MENUA0=
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG